# Generated by Django 3.0.4 on 2020-04-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200423_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo_status',
            field=models.IntegerField(default=0),
        ),
    ]
