# Generated by Django 3.1.7 on 2021-03-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], default='Male', max_length=10),
        ),
    ]
